CREATE TABLE audit_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    server_name VARCHAR(128) NOT NULL,
    computer_name VARCHAR(128) NULL,
    event_id INT NOT NULL,
    record_id BIGINT UNSIGNED NOT NULL,
    time_created DATETIME NOT NULL,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(255) NULL,
    domain_name VARCHAR(255) NULL,
    user_sid VARCHAR(255) NULL,
    source_ip VARCHAR(64) NULL,
    source_port VARCHAR(32) NULL,
    object_name TEXT NULL,
    object_type VARCHAR(128) NULL,
    share_name VARCHAR(512) NULL,
    relative_target_name TEXT NULL,
    action VARCHAR(64) NOT NULL,
    access_mask VARCHAR(64) NULL,
    access_list TEXT NULL,
    handle_id VARCHAR(64) NULL,
    logon_id VARCHAR(64) NULL,
    transaction_id VARCHAR(128) NULL,
    task_category VARCHAR(255) NULL,
    keywords_text VARCHAR(255) NULL,
    process_name TEXT NULL,
    status VARCHAR(64) NULL,
    raw_json JSON NULL,
    UNIQUE KEY uniq_event (server_name, event_id, record_id),
    INDEX idx_time_created (time_created),
    INDEX idx_action_time (action, time_created),
    INDEX idx_username (username),
    INDEX idx_source_ip (source_ip),
    INDEX idx_handle_id (server_name, handle_id),
    INDEX idx_logon_id (server_name, logon_id),
    INDEX idx_event_id_time (event_id, time_created),
    FULLTEXT INDEX ft_object_name (object_name, relative_target_name, share_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dns_queries (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dns_server VARCHAR(128) NOT NULL,
    time_created DATETIME NOT NULL,
    client_ip VARCHAR(64) NOT NULL,
    query_name VARCHAR(1024) NOT NULL,
    query_type VARCHAR(32) NULL,
    response_code VARCHAR(64) NULL,
    entry_hash CHAR(64) NOT NULL,
    raw_line TEXT NULL,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_dns_entry (entry_hash),
    INDEX idx_dns_time (time_created),
    INDEX idx_dns_client_time (client_ip, time_created),
    INDEX idx_dns_query_time (query_name(255), time_created)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
